export type Article = {
  id: number;
  slug: string;
  tag: string;
  date: string;
  title: string;
  subtitle: string;
  desc: string;
  image: string;
  accent: string;
  accentBorder: string;
  accentBg: string;
  readTime: string;
  body: {
    type: "heading" | "para" | "quote" | "list" | "subheading";
    content: string | string[];
  }[];
};

export const articles: Article[] = [
  {
    id: 1,
    slug: "claude-mythos",
    tag: "AI Model Architecture",
    date: "19.04.2026",
    title: "Claude Mythos: Anthropic's Philosophical Leap Beyond Just Safety",
    subtitle: "Why the latest Claude family isn't another benchmark win — it's a fundamental rethinking of what enterprise AI should be.",
    desc: "Anthropic's latest model family isn't just another capability jump—it's a reframing of what AI alignment means in practice. We break down the Mythos architecture paradigm, its constitutional AI upgrades, and why this signals a bifurcation in the enterprise LLM market.",
    image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?auto=format&fit=crop&q=80&w=2670",
    accent: "text-[#e8642a]",
    accentBorder: "border-[#e8642a]/20",
    accentBg: "bg-[#e8642a]/10",
    readTime: "8 min read",
    body: [
      { type: "para", content: "For the past two years, the dominant narrative in enterprise AI has been a horse race — GPT vs Claude vs Gemini, benchmarks vs benchmarks, parameter counts vs parameter counts. Anthropic has just stepped off that track entirely." },
      { type: "heading", content: "What Mythos Actually Changes" },
      { type: "para", content: "The Mythos naming convention is Anthropic's signal that this isn't just a version increment. Where previous Claude models iterated on capability and safety in tandem, Mythos introduces what Anthropic internally calls 'Values Hierarchy Programming' — a layered constitutional structure that doesn't just prevent bad outputs, but actively reasons about why certain outputs serve the user's long-term interests versus short-term requests." },
      { type: "para", content: "In practical terms, this means Claude Mythos can decline to help with something not because a filter flagged it, but because it has built a model of your organisational intent and flagged a misalignment. For BITSS clients operating in healthcare, finance, and defense, this is significant: the model becomes an architectural partner rather than a smart autocomplete." },
      { type: "quote", content: "The difference between safety and alignment is the difference between a guard and a counselor. Mythos is Anthropic's first credible attempt to build the latter." },
      { type: "heading", content: "The Enterprise Bifurcation" },
      { type: "para", content: "The LLM market is splitting into two distinct categories. On one side: raw power models optimised for creative tasks, code generation, and high-throughput unstructured work. On the other: auditable, values-aligned models built for regulated industries where explainability is not optional." },
      { type: "para", content: "Claude Mythos positions itself firmly in the second camp. Its new Reasoning Trace feature outputs a structured log of the model's decision path — something that a compliance officer can actually read and sign off on. This is not a minor UX feature. This is the feature that lets a hospital CIO put Claude into a patient-facing workflow." },
      { type: "subheading", content: "Key Architectural Upgrades in Mythos" },
      { type: "list", content: ["Values Hierarchy Programming — layered constitutional rules with organisational override capability", "Reasoning Trace output — auditable decision logs in structured JSON", "Context Persistence — maintains organisational intent across multi-session deployments", "Selective Disclosure Mode — controls what the model reveals about its own reasoning chain to end users", "Adversarial Robustness v3 — significantly hardened against prompt injection in agentic pipelines"] },
      { type: "heading", content: "The BITSS Take" },
      { type: "para", content: "At BITSS, we've been running private LLM integrations into enterprise stacks for two years. The consistent friction point has never been model quality — it's been governance. Legal teams, compliance officers, and CISOs don't care that a model scored 92% on MMLU. They care about audit trails, data residency, and the ability to point to a decision log when something goes wrong." },
      { type: "para", content: "Claude Mythos is the first model that architecturally addresses this. If you're running an enterprise and you've been waiting to seriously deploy AI into your core operations, the wait is over. This is the model you build on." },
    ],
  },
  {
    id: 2,
    slug: "attention-is-everything",
    tag: "Deep Learning",
    date: "14.04.2026",
    title: "Attention Is Everything: How One 2017 Paper Still Dictates Modern AI",
    subtitle: "Nine years after 'Attention Is All You Need', the transformer still runs the world. Here's why — and where its seams are starting to show.",
    desc: "The 2017 'Attention Is All You Need' paper quietly dismantled decades of recurrent-network dominance and installed transformers as the universal substrate of intelligence. Nine years on, we audit the architectural decision.",
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=2765",
    accent: "text-[#4d7fff]",
    accentBorder: "border-[#4d7fff]/20",
    accentBg: "bg-[#4d7fff]/10",
    readTime: "11 min read",
    body: [
      { type: "para", content: "In June 2017, eight researchers at Google published a 15-page paper titled 'Attention Is All You Need'. It contained no dramatic claims, no breathless press release. It simply proposed replacing the dominant neural architecture of the decade — recurrent neural networks — with something cleaner, faster, and more parallelisable: the transformer." },
      { type: "para", content: "Nine years later, that paper has become the most influential document in the history of computer science. Every frontier AI model — GPT-5, Claude, Gemini, LLaMA — runs on transformer architecture. The attention mechanism described in those 15 pages is the engine underneath everything." },
      { type: "heading", content: "Why Attention Works" },
      { type: "para", content: "The core insight of the transformer is deceptively simple: instead of processing a sequence step by step, process every element in relation to every other element simultaneously. This self-attention mechanism allows the model to learn which parts of an input are relevant to which other parts, regardless of distance." },
      { type: "quote", content: "The transformer didn't just improve performance on existing benchmarks. It made entirely new categories of capability possible — emergent behaviours that nobody predicted and that still aren't fully understood." },
      { type: "heading", content: "The Scaling Miracle" },
      { type: "para", content: "What nobody anticipated in 2017 was what would happen when you simply made transformers bigger and fed them more data. Starting around 2020, researchers began documenting emergent capabilities — abilities that models suddenly developed at scale that weren't present at smaller sizes. Chain-of-thought reasoning. In-context learning. Code generation. These weren't trained explicitly. They appeared." },
      { type: "subheading", content: "Where the Seams Are Showing" },
      { type: "list", content: ["Context window limitations — even at 1M tokens, transformers struggle with very long-range dependencies", "Quadratic attention cost — computing attention across N tokens costs O(N²)", "No persistent memory — transformers have no native long-term memory independent of context", "Hallucination — confident fabrication of information remains an unsolved structural problem", "Energy inefficiency — the compute density required is environmentally and economically unsustainable at scale"] },
      { type: "heading", content: "What Comes Next" },
      { type: "para", content: "State Space Models like Mamba offer linear-time sequence modeling. Mixture of Experts architectures allow massive parameter counts with selective activation. Hybrid approaches combining transformers with external memory stores are showing promise in agentic settings. But the transformer won't be dethroned soon — the ecosystem around it represents trillions of dollars of embedded investment. For now, attention really is all you need." },
    ],
  },
  {
    id: 3,
    slug: "cloudflare-one-line-error",
    tag: "Infrastructure Postmortem",
    date: "09.04.2026",
    title: "How One Missing Character Took Down Cloudflare's Global Network",
    subtitle: "A BGP routing misconfiguration that propagated in minutes. The lessons for every engineering team that runs production infrastructure.",
    desc: "A single erroneous character in a BGP routing rule briefly knocked Cloudflare off the internet for millions of users. This is a masterclass in why infrastructure at scale demands immutable configuration pipelines.",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=2534",
    accent: "text-[#2fd4a0]",
    accentBorder: "border-[#2fd4a0]/20",
    accentBg: "bg-[#2fd4a0]/10",
    readTime: "9 min read",
    body: [
      { type: "para", content: "On April 9th, 2026, Cloudflare experienced a partial global outage lasting approximately 34 minutes. The root cause: a single character missing from a BGP route filter configuration that was pushed to production without adequate staged rollout." },
      { type: "heading", content: "What Actually Happened" },
      { type: "para", content: "The configuration change was valid in isolation — but contained a prefix length specification that, due to a missing character, accepted a broader range of route announcements than intended. The change passed automated validation. It was pushed to a canary set of POPs, but the canary monitoring window was 4 minutes — too short to catch propagation-dependent failures." },
      { type: "quote", content: "The validator checked that the configuration was syntactically correct. Nobody checked that it was semantically safe. Those are two completely different things — and confusing them is how outages happen." },
      { type: "heading", content: "The Cascade" },
      { type: "para", content: "Once Cloudflare's edge nodes began advertising incorrect routes, upstream providers and peers began accepting and re-advertising them. The blast radius expanded from a few POPs to affecting global routing tables within 8 minutes. By the time engineers began emergency rollback, the change was already in routers they didn't directly control." },
      { type: "subheading", content: "The 5 Failures That Compounded" },
      { type: "list", content: ["Semantic validation gap — CI/CD pipeline validated syntax, not impact radius", "Insufficient canary window — 4 minutes is not long enough to observe BGP propagation effects", "Missing blast radius guardrails — no maximum-prefix limits on what the configuration change could affect", "No automated rollback trigger — rollback was initiated manually, adding 6-8 minutes to MTTR", "Alert fatigue — the initial BGP deviation alerts were deprioritised because they triggered frequently during normal operations"] },
      { type: "heading", content: "The BITSS Infrastructure Standard" },
      { type: "para", content: "Every production deployment BITSS engineers touches is built around what we call the Zero-Blast-Radius Protocol. Every configuration change must pass three gates before production: syntactic validation, semantic impact simulation, and blast-radius quantification. The semantic impact simulation is the gate most teams skip because it's hard to build. But it's the gate that would have caught this error before it touched a single production router." },
    ],
  },
  {
    id: 4,
    slug: "vibe-coding-enterprise",
    tag: "AI & Dev Trends",
    date: "02.04.2026",
    title: "Vibe Coding is Real — And It's Coming For Enterprise Dev Teams",
    subtitle: "AI-first development is no longer a hobbyist curiosity. It's restructuring how enterprise software gets built, reviewed, and owned.",
    desc: "The rise of AI-first development workflows — Cursor, Claude Code, Copilot Workspace — is changing what a software team looks like. For enterprise, the implications are profound: fewer engineers, faster timelines, and entirely new failure modes.",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=2670",
    accent: "text-[#8b5cf6]",
    accentBorder: "border-[#8b5cf6]/20",
    accentBg: "bg-[#8b5cf6]/10",
    readTime: "10 min read",
    body: [
      { type: "para", content: "Andrej Karpathy coined the term 'vibe coding' in early 2025 to describe a new mode of software development: describe what you want to an AI, accept what it generates, iterate by feel. The name was partly joking. The phenomenon it describes is not." },
      { type: "para", content: "By Q1 2026, tools like Cursor, Claude Code, and GitHub Copilot Workspace have generated a documented shift in how enterprise codebases are actually built. Developers who previously spent 60% of their time writing boilerplate now spend 60% of their time reviewing and steering AI output. The work hasn't disappeared — it's transformed." },
      { type: "heading", content: "What's Actually Changed in Enterprise" },
      { type: "para", content: "The most significant shift isn't in speed — though AI-assisted developers do ship features 30-60% faster by most measures. It's in the composition of engineering teams. Enterprises that formerly needed 12-person development squads for a major system build are running equivalent projects with 5-person teams where 3 of those people are primarily doing AI-augmented engineering." },
      { type: "quote", content: "The question is no longer whether your team uses AI to write code. It's whether you have the code review infrastructure to safely govern what the AI produces at scale." },
      { type: "heading", content: "The New Failure Modes" },
      { type: "para", content: "Vibe coding introduces failure modes that traditional software engineering practices weren't designed to catch. When code is generated by an AI and accepted without deep inspection, patterns emerge that look correct locally but are architecturally wrong at scale: subtle N+1 query patterns, missing error propagation, security-adjacent assumptions baked into generated authentication logic." },
      { type: "subheading", content: "The Enterprise Risk Surface" },
      { type: "list", content: ["AI hallucinated dependencies — packages referenced in generated code that don't exist or have known vulnerabilities", "Invisible technical debt — AI-generated code often optimises for readability while hiding performance debt", "Review bottlenecks — when every commit is AI-assisted, senior engineering review becomes the critical path", "IP liability grey zones — ownership of AI-generated code in B2B contracts remains legally unsettled", "Prompt injection in agentic pipelines — AI coding agents with filesystem access create new attack surfaces"] },
      { type: "heading", content: "How BITSS Uses AI-Assisted Development" },
      { type: "para", content: "At BITSS, we've integrated AI-assisted development into our workflow with strict governance gates. AI generates; senior engineers architect and review. Every AI-assisted commit passes our semantic review checklist before merge. We've cut feature development time by approximately 40% while maintaining the zero-defect production record our defense and enterprise clients require." },
      { type: "para", content: "The future of enterprise software development isn't AI replacing engineers. It's engineers who know how to govern AI output replacing engineers who don't." },
    ],
  },
  {
    id: 5,
    slug: "edge-ai-iot",
    tag: "IoT & Hardware",
    date: "25.03.2026",
    title: "Why Every IoT Fleet Will Run on Edge AI by 2027",
    subtitle: "On-device inference is no longer a research project. It's the only viable architecture for the next generation of connected hardware.",
    desc: "The convergence of on-device inference — LLaMA on-device, Apple Neural Engine, Qualcomm NPUs — is making cloud-dependent IoT architectures obsolete. Here's what the transition looks like and why it's happening faster than anyone expected.",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=2670",
    accent: "text-[#ec4899]",
    accentBorder: "border-[#ec4899]/20",
    accentBg: "bg-[#ec4899]/10",
    readTime: "9 min read",
    body: [
      { type: "para", content: "For the past decade, the dominant IoT architecture has been: device collects data, sends it to the cloud, cloud processes it, sends instructions back. This architecture has three fatal flaws: it requires constant connectivity, it introduces latency that's unacceptable for real-time control systems, and it creates a single point of failure that can take down an entire device fleet simultaneously." },
      { type: "para", content: "Edge AI — running inference models directly on the device — solves all three. And as of 2026, it's no longer a research-grade capability. It's shipping in production hardware." },
      { type: "heading", content: "The Hardware That Made This Possible" },
      { type: "para", content: "Three hardware developments converged to make edge AI practical at scale. Apple's Neural Engine (now in its 5th generation) can run 7B-parameter quantised models locally. Qualcomm's Snapdragon X NPU achieves 45 TOPS on-device. And perhaps most importantly for IoT specifically, the Raspberry Pi 5's newer AI HAT adds 26 TOPS to a $100 board — bringing meaningful inference to industrial and embedded deployments for the first time." },
      { type: "quote", content: "The question stopped being 'can we run AI on the device'. The question is now 'why would we run it anywhere else'." },
      { type: "heading", content: "Real-World Architecture Implications" },
      { type: "para", content: "For BITSS engineering teams deploying IoT systems — such as our Shanmukhananda Hall infrastructure project — the shift to edge AI changes the entire system architecture. Instead of a hub-and-spoke model where intelligence lives in the cloud, edge AI enables a mesh architecture where each node is capable of independent inference." },
      { type: "subheading", content: "What Changes with Edge AI Architecture" },
      { type: "list", content: ["Offline-first becomes the default — devices operate fully without internet connectivity", "Latency drops from 100-300ms (cloud round-trip) to <5ms (local inference)", "Data sovereignty becomes structurally enforced — sensitive data never leaves the device", "Fleet resilience improves — no central cloud point of failure", "Bandwidth costs drop dramatically — raw sensor data stays local, only processed insights are transmitted"] },
      { type: "heading", content: "The 2027 Transition Point" },
      { type: "para", content: "Our projection: by end of 2027, more than 60% of new enterprise IoT deployments will specify edge inference as a core architectural requirement, not an optional feature. The drivers are regulatory (GDPR and India's DPDP Act make cloud-first data architectures riskier), economic (cloud inference costs at fleet scale are prohibitive), and competitive (edge AI enables capabilities that cloud-dependent systems simply cannot match in latency-sensitive applications)." },
    ],
  },
  {
    id: 6,
    slug: "react-native-renaissance",
    tag: "Mobile Architecture",
    date: "18.03.2026",
    title: "The React Native Renaissance: Why Enterprise is Coming Back",
    subtitle: "After years of Flutter and native debates, React Native's New Architecture is winning enterprise mobile back. Here's what changed.",
    desc: "React Native 0.74 and the New Architecture have resolved the performance and reliability issues that drove enterprises to Flutter and native alternatives. The pendulum is swinging back — and this time, the technical case is solid.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=2670",
    accent: "text-[#14b8a6]",
    accentBorder: "border-[#14b8a6]/20",
    accentBg: "bg-[#14b8a6]/10",
    readTime: "8 min read",
    body: [
      { type: "para", content: "Between 2020 and 2023, React Native had a reputation problem. Bridge-based architecture introduced latency. The JavaScript thread was a bottleneck. Hermes improved startup times, but the fundamental async communication between JS and native layers meant that genuinely smooth 60fps UI was difficult to guarantee. Enterprise clients — particularly in finance and logistics where UI jank directly impacts productivity — moved to Flutter or went native." },
      { type: "para", content: "React Native 0.74, released in 2024, and the subsequent full enablement of the New Architecture in 0.75, changed the equation. The bridge is gone. JSI (JavaScript Interface) provides synchronous, direct communication between JavaScript and native code. Fabric renders the UI on the native thread. Turbo Modules load natively on demand. The performance characteristics are fundamentally different." },
      { type: "heading", content: "What the New Architecture Actually Delivers" },
      { type: "para", content: "The numbers that matter for enterprise: startup time is down 40% versus bridge-based React Native. Scroll performance on complex lists is now indistinguishable from native in controlled benchmarks. Memory pressure from the JavaScript runtime has been reduced through better garbage collection scheduling coordinated with Fabric's render cycle." },
      { type: "quote", content: "We ran the same logistics tracking interface in Flutter, native Swift/Kotlin, and React Native New Architecture. The RN build was within 3% on every performance metric and took 35% less engineering time to ship." },
      { type: "heading", content: "The Enterprise Calculus" },
      { type: "para", content: "For an enterprise choosing a mobile stack in 2026, the calculus has changed. Flutter requires Dart — a language most enterprise teams don't have in their talent pool. Native requires separate iOS and Android codebases, roughly doubling ongoing maintenance costs. React Native New Architecture delivers near-native performance while leveraging the JavaScript/TypeScript talent pool that enterprise teams already have." },
      { type: "subheading", content: "Why BITSS Builds on React Native" },
      { type: "list", content: ["Single codebase for iOS, Android, and (via React Native Web) browser — one team owns all platforms", "Shared business logic with Next.js web apps — types, validation, and API clients are reused across mobile and web", "OTA updates via Expo EAS — enterprise can push bug fixes without App Store review cycles", "Offline-first with WatermelonDB — complex relational data works reliably without connectivity", "New Architecture JSI modules — native performance for compute-intensive features like biometric auth and camera processing"] },
      { type: "heading", content: "The Projects That Proved It" },
      { type: "para", content: "Our Kamdhenu Protocol real estate management platform, Dunamis project tracking system, and Oxygen Commerce Fleet — all built on React Native — are in daily production use by enterprise teams running critical operations. The performance issues that plagued React Native in 2021 are not present in these systems. The renaissance is real." },
    ],
  },
  {
    id: 7,
    slug: "india-govtech-opportunity",
    tag: "Enterprise & Policy",
    date: "10.03.2026",
    title: "India's GovTech Stack is a ₹4L Crore Opportunity — And Nobody is Building it Right",
    subtitle: "ONDC, GeM, DigiLocker, UPI-linked B2B rails are in place. The software layer that sits on top of them is almost entirely missing.",
    desc: "India's digital public infrastructure is world-class. The private software that should be leveraging it is mostly generic, largely underfunded, and frequently built by teams that don't understand the underlying APIs. A builder's perspective on the biggest untapped opportunity in Indian tech.",
    image: "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?auto=format&fit=crop&q=80&w=2670",
    accent: "text-[#f59e0b]",
    accentBorder: "border-[#f59e0b]/20",
    accentBg: "bg-[#f59e0b]/10",
    readTime: "12 min read",
    body: [
      { type: "para", content: "India has quietly built the most sophisticated digital public infrastructure stack in the world. Aadhaar handles 1.3 billion identity verifications. UPI processes over 13 billion transactions per month. ONDC is disaggregating e-commerce. GeM is digitising government procurement. DigiLocker holds 6 billion documents. The India Stack is genuinely world-class." },
      { type: "para", content: "The software that sits on top of it is, with rare exceptions, terrible. Generic SaaS built in Bangalore with no deep understanding of the APIs. Legacy systems that predate the stack and haven't been replaced. Manual workarounds for digital processes that should be automated. The infrastructure layer is a 10x investment. The application layer is a 0.1x investment. The gap is the opportunity." },
      { type: "heading", content: "What the Stack Actually Enables" },
      { type: "para", content: "Most Indian enterprise software teams treat GeM as a website you go to manually. BITSS built GeM SaaS for Archana Associates — a system that programmatically monitors tenders matching their capability profile, auto-generates compliance documents, and submits bids with minimal human intervention. The GeM API makes all of this possible. Almost nobody is building on it this way." },
      { type: "quote", content: "The competitive moat for the next generation of Indian enterprise software isn't the product features. It's depth of API integration with the India Stack. The teams that master this will be untouchable." },
      { type: "subheading", content: "The Highest-Value Unbuilt Applications" },
      { type: "list", content: ["ONDC-native commerce intelligence — real-time competitive pricing and inventory analytics across the open network", "GeM automation suites — end-to-end government procurement systems for consultancies and contractors averaging ₹50Cr+ in annual tender volume", "DigiLocker enterprise connectors — automated document verification pipelines for NBFC, insurance, and HR workflows", "UPI B2B credit rails — embedded credit products using UPI transaction history as underwriting data", "DPDP compliance engines — automated data residency and consent management for enterprises navigating India's new data protection regime"] },
      { type: "heading", content: "The Builder's Perspective" },
      { type: "para", content: "Having built on GeM APIs directly, our experience is that the documentation is better than most private sector APIs we work with. The authentication flows are well-designed. The rate limits are generous. The problem isn't that the stack is hard to build on. The problem is that most software teams in India learned to build on Shopify and AWS before they learned to build on the India Stack." },
      { type: "para", content: "That's changing. The next 3 years will produce a cohort of Indian software companies with deep India Stack integration as their core competency. The ones that move first will compound their advantage. We are building for that future — and we're looking for enterprise partners who want to build with us." },
    ],
  },
  {
    id: 8,
    slug: "microservices-modular-monolith",
    tag: "System Architecture",
    date: "01.03.2026",
    title: "Microservices Were a Mistake. Here's What Comes Next.",
    subtitle: "The industry's honest reckoning with a decade of over-engineered distributed systems — and the pragmatic architecture that's replacing them.",
    desc: "The backlash against microservices is no longer contrarian. It's mainstream. Amazon, Shopify, and Stack Overflow have publicly document their returns to consolidated architectures. We examine why it happened and what the modular monolith actually delivers.",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=2670",
    accent: "text-[#6366f1]",
    accentBorder: "border-[#6366f1]/20",
    accentBg: "bg-[#6366f1]/10",
    readTime: "13 min read",
    body: [
      { type: "para", content: "In 2015, microservices were the future of software architecture. Netflix published their journey. Amazon decomposed their monolith. Thoughtworks put microservices on their technology radar as 'adopt'. Engineering conferences were overwhelmed with talks about service meshes, distributed tracing, and event-driven choreography. The monolith was officially dead." },
      { type: "para", content: "In 2026, Amazon Prime Video publicly documented moving a critical streaming pipeline from microservices back to a monolith — reducing their infrastructure costs by 90% and cutting operational complexity dramatically. Shopify has operated on a Rails monolith for most of its existence and openly credits it for their ability to ship fast. Stack Overflow serves billions of page views per month from a small cluster of .NET servers. The monolith is not dead. The religion around microservices is." },
      { type: "heading", content: "What Went Wrong" },
      { type: "para", content: "Microservices solve real problems — but only at the scale where those problems actually exist. Netflix operates at a scale where independent deployability of 700 services is worth the operational overhead of managing 700 services. The median enterprise does not operate at Netflix scale. They operate at a scale where microservices introduce the complexity of distributed systems without the scale that justifies it." },
      { type: "quote", content: "The right architecture for your system's current scale is almost never the architecture that would be right if you were 10x bigger. Optimising for the scale you don't have yet is how you build systems that are expensive to operate and slow to change." },
      { type: "heading", content: "The Distributed Systems Tax" },
      { type: "para", content: "Every microservices architecture pays what we call the Distributed Systems Tax: network calls that can fail, partial failure modes that don't exist in a monolith, distributed transactions that require saga patterns or two-phase commit, observability that requires distributed tracing infrastructure, and deployment complexity that requires a platform engineering team just to manage the deployment pipeline." },
      { type: "subheading", content: "The Hidden Costs Most Teams Don't Count" },
      { type: "list", content: ["Service mesh operation — Istio or Linkerd require dedicated platform engineering headcount to operate correctly", "Distributed tracing overhead — Jaeger or Tempo add 3-8% latency overhead and significant storage costs", "Schema evolution across service boundaries — changing a shared data model requires coordinated deployment of multiple services", "Integration testing complexity — testing interactions between 20 services requires 20-service test environments", "On-call cognitive load — debugging a production issue that spans 8 services requires 8x the mental model of debugging a monolith"] },
      { type: "heading", content: "The Modular Monolith" },
      { type: "para", content: "The modular monolith — a single deployable unit with strong internal module boundaries — is not a step backward. It's a more honest architecture. Modules own their data and logic. Interfaces between modules are explicit. The monolith can be deployed to multiple instances for scale. When a specific module genuinely requires independent scaling or deployment, it can be extracted — at which point you have microservices where they're actually justified." },
      { type: "heading", content: "The BITSS Approach" },
      { type: "para", content: "For the enterprise systems we architect at BITSS, the default starting point is a well-structured Next.js application with clear domain boundaries and a single Postgres database. This is not 'beginner architecture'. For most enterprise problems — even at significant scale — it is the correct architecture. We extract to separate services when a module has a genuinely different scaling profile, requires a different technology, or needs independent deployment for security isolation. Not before." },
    ],
  },
];

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find((a) => a.slug === slug);
}
